AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Supper Bot

Resources:
  SupperBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: supper-bot/
      Environment:
        Variables:
          BOT_ID: CHANGE_ME
          BOT_TOKEN: CHANGE_ME
          BOT_URL: t.me/CHANGE_ME
          TABLE_NAME: supper-bot
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies:
        - DynamoDBCrudPolicy:
            TableName: supper-bot
      ReservedConcurrentExecutions: 5
      Timeout: 3
      Events:
        TelegramWebhook:
          Type: Api
          Properties:
            Path: /telegram-X7BZfDi8v8
            Method: post

  SupperBotTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: chat_id
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N
      BillingMode: PROVISIONED
      KeySchema:
        - AttributeName: chat_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: supper-bot
